<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
	'ID' => 'ID',
	'ParentID' => 'ParentID',
	'Displayname' => 'Displayname',
	'Category' => 'Category',
	'Media Type' => 'Media Type',
	'Filesize' => 'Filesize',
	'File Name' => 'File Name',
	'File Path' => 'File Path',
	'Mime Type' => 'Mime Type',
	'Dimension Width' => 'Dimension Width',
	'Dimension Height' => 'Dimension Height',
	'Meta Keywords' => 'Meta Keywords',
	'Meta Description' => 'Meta Description',
	'Modification Datetime' => 'Modification Datetime',
	'Modification Userid' => 'Modification Userid',
	'Created Datetime' => 'Created Datetime',
	'Createdby Userid' => 'Createdby Userid',
	'Parent Content media ID' => 'Parent Content media ID',
	'Mime Type' => 'Mime Type',
	'Search' => 'Search',
	'Reset' => 'Reset',
	'Update' => 'Update',
	'Continue' => 'Continue',
	'expand folders until {0,ordinal} level' => 'expand folders until {0,ordinal} level',
	'menu item name' => 'menu item name',
	'type' => 'type',
	'displayed' => 'displayed',
	'item languages' => 'item languages',
	'status' => 'status',
	'Cancel' => 'Cancel',
	'The page could not be found in the requested language, displaying fallback language instead' => 'The page could not be found in the requested language, displaying fallback language instead',
];