<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
	'ID' => 'ID',
	'ParentID' => 'ParentID',
	'Parent ID' => 'Parent ID',
	'Displayname' => 'Displayname',
	'Category' => 'Category',
	'Media Type' => 'Media Type',
	'Filesize' => 'Filesize',
	'File Name' => 'File Name',
	'File Path' => 'File Path',
	'Mime Type' => 'Mime Type',
	'Dimension Width' => 'Dimension Width',
	'Dimension Height' => 'Dimension Height',
	'Meta Keywords' => 'Meta Keywords',
	'Meta Description' => 'Meta Description',
	'Modification Datetime' => 'Modification Datetime',
	'Modification Userid' => 'Modification Userid',
	'Created Datetime' => 'Created Datetime',
	'Createdby Userid' => 'Createdby Userid',
	'Parent Content media ID' => 'Parent Content media ID',
	'Mime Type' => 'Mime Type',
	'Search' => 'Search',
	'Reset' => 'Reset',
	'Update' => 'Update',
	'Continue' => 'Continue',
	'expand folders until {0,ordinal} level' => 'expand folders until {0,ordinal} level',
	'menu item name' => 'menu item name',
	'type' => 'type',
	'displayed' => 'displayed',
	'item languages' => 'item languages',
	'status' => 'status',
	'Cancel' => 'Cancel',
	'The page could not be found in the requested language, displaying fallback language instead' => 'The page could not be found in the requested language, displaying fallback language instead',
	'CMS Administration' => 'CMS Administration',
	'Content linked to Menu language version' => 'Content linked to Menu language version',
	'Error: content saved, yet it could not be linked to the menu language version!' => 'Error: content saved, yet it could not be linked to the menu language version!',	
	'Content saved successfully' => 'Content saved successfully',
	'Error: saving content failed!' => 'Error: saving content failed!',
	'Menu details saved successfully' => 'Menu details saved successfully',
	'Error: saving new menu name!' => 'Error: saving new menu name!',
	'Document saved successfully' => 'Document saved successfully',
	'Error: saving document failed!' => 'Error: saving document failed!',
	'Menu details saved successfully' => 'Menu details saved successfully',
	'Error: saving new menu name!' => 'Error: saving new menu name!',
	'Menu details saved successfully' => 'Menu details saved successfully',
	'Error: saving new menu name!' => 'Error: saving new menu name!',
	'Error while trying to save new menu item: ' => 'Error while trying to save new menu item: ',
	'Language' => 'Language',
	'Presentation Style' => 'Presentation Style',
	'Position' => 'Position',
	'Display State' => 'Display State',
	'You can drag and drop menu items to rearange them (use the menu name for dragging). Right clicking on the menu name reveals a context menu to create new menu items.' => 'You can drag and drop menu items to rearange them (use the menu name for dragging). Right clicking on the menu name reveals a context menu to create new menu items.',
    'read more...' => 'read more...',
];